// <auto-generated />
using Cardcraft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cardcraft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Cardcraft.Data.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Family")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 3,
                            Cost = 0,
                            Description = "An unemployed programmer.",
                            Family = 0,
                            Health = 2,
                            Image = "images/buff_programmer.png",
                            IsActive = false,
                            Name = "Mayo"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 1,
                            Cost = 0,
                            Description = "A tiny berserker chihuahua.",
                            Family = 3,
                            Health = 1,
                            Image = "images/boloberto.png",
                            IsActive = false,
                            Name = "Bolo"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 2,
                            Cost = 0,
                            Description = "An tall exotic voluptuous woman.",
                            Family = 0,
                            Health = 3,
                            Image = "images/exotic_island_girl.png",
                            IsActive = false,
                            Name = "Cami"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
